#cloud-config
users:
  - name: ${vm_user}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILv3myr1jU9B/rEvLPAxsvOGm1QTEz0mdHic7FhqEr6K pavel@debian-laptop
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEf2tSZ8i9kZvwM3On8neMlB+jJy8yU34s3yF+BSGP71 user@WINDOWS-QFD8JJ4

write_files:
  - path: "/usr/local/etc/init.sh"
    permissions: "755"
    content: |
      #!/bin/bash

      echo "Installing Docker"
      sudo apt update -y && sudo apt install docker.io -y
      echo "Grant user access to Docker"
      sudo usermod -aG docker ${vm_user}
      newgrp docker
      echo "Installing Docker compose"
      sudo apt install docker-compose -y
    defer: true
runcmd:
  - [su, ubuntu, -c, "/usr/local/etc/init.sh"]