apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "kubernetes-pods"
        metrics_path: /actuator/prometheus
        kubernetes_sd_configs:
        - role: pod

    remote_write:
      - url: 'https://monitoring.api.cloud.yandex.net/prometheus/workspaces/mon4qajkk17258krfi6g/api/v1/write'
        bearer_token: "${YC_PROM_KEY}"
        queue_config:
          max_samples_per_send: 2000
          min_backoff: 100ms
          max_backoff: 15s
          retry_on_http_429: true
        metadata_config:
          send: false