global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]

remote_write:
  - url: 'https://monitoring.api.cloud.yandex.net/prometheus/workspaces/mon4qajkk17258krfi6g/api/v1/write'
    bearer_token_file: 'ajeqnqo3grff5urh3dna'
    queue_config:
      max_samples_per_send: 2000
      min_backoff: 100ms
      max_backoff: 15s
      retry_on_http_429: true
    metadata_config:
      send: false

